# API проксі
[[redirects]]
  from = "/api/*"
  to = "https://obminbook.us-east-1.elasticbeanstalk.com/:splat"
  status = 200

# SPA fallback тільки для неіснуючих файлів (без force)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200