# Проксі для API
[[redirects]]
  from = "/api/*"
  to = "http://obminbook.eu-central-1.elasticbeanstalk.com/"
  status = 200
  force = true

# SPA fallback для всіх інших маршрутів
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
